- hosts: webservers
  vars:
      http_port: 999
      server_name: "web"
      message: "Hello world"
  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: (Re)start the nginx server
      shell: pkill nginx; pwait nginx; nginx

    - name: Copy nginx config
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
      notify:
        - Restart the nginx server

    - name: Add the index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html

  handlers:
    - name: Restart the nginx server
      shell: pkill nginx; pwait nginx; nginx
