version: "3.8"
services:
  ansible:
    hostname: ansible
    tty: true
    networks:
      - containers
    volumes:
      - ./shared-folder:/shared-folder
    build:
      context: .
      dockerfile: Dockerfile.ansible
  web:
    ports:
      - "5001-5005:999"
    networks:
      - containers
    build:
      context: .
      dockerfile: Dockerfile.debian
    deploy:
      replicas: 5

  db:
    hostname: db
    networks:
      - containers
    build:
      context: .
      dockerfile: Dockerfile.alpine

  whatsmydns:
    hostname: wmdns
    ports:
      - 5000:7878
    networks:
      - containers
    build:
      context: .
      dockerfile: Dockerfile.whatsmydns

  nameserver:
    hostname: nserver
    image: coredns/coredns
    ports:
      - 53/udp
      - 53/tcp
    volumes:
      - ./dns-data:/dns
    networks:
      containers:
        ipv4_address: 172.20.15.11
    command:
      - --conf=/dns/Corefile

networks:
  containers:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.15.0/24
          ip_range: 172.20.15.0/24
