FROM alpine

COPY id_rsa.pub /root/.ssh/authorized_keys

RUN apk add --no-cache openssh-server python3 && ssh-keygen -A && echo 'root:root' | chpasswd

RUN chmod 400 /root/.ssh/authorized_keys

ENTRYPOINT echo "My hostname is $(hostname)" && /usr/sbin/sshd -D -e
