FROM ubuntu:22.10

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-add-repository --yes --update ppa:ansible/ansible
RUN apt-get install -y ansible iputils-ping python3-apt vim tree curl

ADD id_rsa /root
RUN cd /root && mkdir /root/.ssh/
RUN cp /root/id_rsa /root/.ssh/
RUN chmod 400 /root/.ssh/id_rsa
RUN chmod 400 /root/id_rsa
RUN echo 'StrictHostKeyChecking=no' >> /etc/ssh/ssh_config

ENTRYPOINT rm /root/.ssh/known_hs;  /bin/bash
