FROM simulatan/whatsmydns

COPY id_rsa.pub /root/.ssh/authorized_keys

RUN apk add --no-cache openssh-server python3 && ssh-keygen -A && echo 'root:root' | chpasswd

RUN chmod 400 /root/.ssh/authorized_keys

RUN echo $'\n\
echo "My hostname is $(hostname)"\n\
/usr/sbin/sshd -D -e &\n\
./app' >> /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT /entrypoint.sh

